# Generated by Django 5.2 on 2025-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lifestyle_user_life_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aimed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aimed_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
