# Generated by Django 5.2 on 2025-07-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='activity_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
