# Generated by Django 5.2 on 2025-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lifestyle_activity_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestyle',
            name='activity_factor',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
