# Generated by Django 5.2 on 2025-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_lifestyle_activity_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='life_style',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20, null=True),
        ),
    ]
