# Generated by Django 5.2 on 2025-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_life_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='life_style',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Active', 'Active'), ('Very active', 'Very active')], max_length=20, null=True),
        ),
    ]
