# Generated by Django 5.2 on 2025-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_life_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aimed_water_intake',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
        ),
    ]
