# Generated by Django 5.2 on 2026-01-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_aimed_water_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntakeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_ml', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='water_intake_goal_ml',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='water_intake_type_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.waterintaketype'),
        ),
    ]
