# Generated by Django 5.2 on 2026-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_waterintaketype_user_water_intake_goal_ml_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntakeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterintaketype',
            name='amount_ml',
        ),
    ]
