# Generated by Django 5.2 on 2026-02-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_waterintakeunit_remove_waterintaketype_amount_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintaketype',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.waterintakeunit'),
            preserve_default=False,
        ),
    ]
