# Generated by Django 5.2 on 2026-02-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_waterintaketype_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintaketype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.waterintakeunit'),
        ),
    ]
