# Generated by Django 5.2 on 2026-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_waterintaketype_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterintaketype',
            name='unit',
        ),
    ]
