# Generated by Django 5.2 on 2026-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_waterintaketype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintaketype',
            name='amount_ml',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
