# Generated by Django 5.2 on 2025-12-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterintaketype',
            old_name='type_name',
            new_name='name',
        ),
    ]
