# Generated by Django 5.2 on 2025-12-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_type_name_waterintaketype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food.mealtype'),
        ),
    ]
