# Generated by Django 5.2 on 2026-01-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_fooditem_calcium_fooditem_iron_fooditem_potassium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='calcium',
            new_name='mineral_calcium',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='iron',
            new_name='mineral_iron',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='potassium',
            new_name='mineral_potassium',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='sodium',
            new_name='mineral_sodium',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='zink',
            new_name='mineral_zink',
        ),
    ]
