# Generated by Django 5.2 on 2026-01-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_calcium_fooditem_mineral_calcium_and_more'),
        ('users', '0010_waterintaketype_user_water_intake_goal_ml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintake',
            name='intake_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to='users.waterintaketype'),
        ),
        migrations.DeleteModel(
            name='WaterIntakeType',
        ),
    ]
